# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('text', models.TextField(verbose_name='texte')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de publication')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nom')),
                ('filename', models.CharField(max_length=100, verbose_name='nom du fichier')),
            ],
            options={
                'verbose_name': 'ic\xf4ne de messages',
                'verbose_name_plural': 'ic\xf4nes de messages',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='icon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paiji2_forum.MessageIcon', verbose_name='ic\xf4ne'),
        ),
        migrations.AddField(
            model_name='message',
            name='question',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='paiji2_forum.Message', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='message',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='lecteurs'),
        ),
    ]
